name: Development CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Development

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
      IMAGE_TAG: ${{ secrets.DOCKER_IMAGE_TAG }}
      PLATFORM:  ${{ secrets.PLATFORM }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Ensure Docker Buildx is set up
          docker buildx create --use || true
          docker buildx inspect --bootstrap

          # Build and push the Docker image for the specified platform
          docker buildx build --platform $PLATFORM -t $IMAGE_NAME:$IMAGE_TAG --push .

      - name: Log out from Docker Hub
        run: docker logout
