name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      IMAGE_NAME: "thanhlp188/whale-project"
      IMAGE_TAG: "v2_amd64"
      PLATFORM: "linux/amd64"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ZIPKIN_COLLECTOR_ENDPOINT: ${{ vars.ZIPKIN_COLLECTOR_ENDPOINT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Ensure Docker Buildx is set up
          docker buildx create --use || true
          docker buildx inspect --bootstrap

          # Build and push the Docker image for the specified platform
          docker buildx build --platform $PLATFORM -t $IMAGE_NAME:$IMAGE_TAG --build-arg ZIPKIN_COLLECTOR_ENDPOINT=$ZIPKIN_COLLECTOR_ENDPOINT --push .

      - name: Log out from Docker Hub
        run: docker logout